### ISSUE TITLE
Layer weight shape missmatch

### ISSUE THREAD

**Issue by hrtavakoli** [marcellacornia/mlnet#1]
Running the method for test using the provided weights receive the following exception:

Exception: Layer weight shape (3, 3, 640, 64) not compatible with provided weight shape (64, 3, 3, 3)

**Comment by baraldilorenzo** [comment]
Hi @hrtavakoli, which backend are you using? MLNet supports Theano only.

**Comment by hrtavakoli** [comment]
Hi @baraldilorenzo, I am using theano backend. The error is from the ml_net_module function  

model = ml_net_model(img_cols=shape_c, img_rows=shape_r, downsampling_factor_product=10)

where  

conv1_1 = Convolution2D(64, 3, 3, weights=weights, activation='relu', border_mode='same')(input_ml_net)

is reached. It seems there is something wrong with the weight file of VGG network weights loaded into the memory.

**Comment by hrtavakoli** [comment]
Solved!

**Comment by baraldilorenzo** [comment]
Glad to hear that! We are trying to replicate the issue. Which was your Keras version and what did you do to solve?

**Comment by hrtavakoli** [comment]
Hi,
It was a misconfiguration in the back-end. Basically,  if you forget to change the data type, but change the backend type, you would get such a nasty phenomena. 

Bests,Hamed

```
On Monday, October 3, 2016 12:19 PM, Lorenzo Baraldi <notifications@github.com> wrote:
```

 Glad to hear that! We are trying to replicate the issue. Which was your Keras version and what did you do to solve?—

**Comment by shaymush** [comment]
Hi @hrtavakoli , I'm getting the same phenomena. 
What exactly did you change in the config file?

**Comment by rabeya-akter** [comment]
> Solved!

how did you solve this?
