### ISSUE TITLE
Loading model error

### ISSUE THREAD

**Issue by ltnghia** [marcellacornia/mlnet#11]
Hi, when I load the model, this error always happens: `Layer weight shape (3, 3, 640, 64) not compatible with provided weight shape (64, 3, 3, 3)`

How can I fix it?
Thanks

**Comment by marcellacornia** [comment]
Hi @ltnghia,
thanks for downloading our code.

Please check your Keras and Theano versions. This code is compatible with Keras 1.1.0 using Theano as backend. 

Your `keras.json` file should have the following format:

```
{
    "image_dim_ordering": "th", 
    "epsilon": 1e-07, 
    "floatx": "float32", 
    "backend": "theano"
}
```
