### ISSUE TITLE
about your provided weights of ML-Net

### ISSUE THREAD

**Issue by ArchWing** [marcellacornia/mlnet#13]
Hi marcella:
  I wonder know whether the weights of ML-Net you provide is only trained on SALICON or have been fine-tuned on MIT1003.
  Thanks for your help!

**Comment by marcellacornia** [comment]
Hi @ArchWing,
thanks for downloading our code.

The weights we provided were obtained by training the ML-Net on the SALICON dataset (2015 release), only.

**Comment by ArchWing** [comment]
@marcellacornia 
thank you so much!
