### ISSUE TITLE
About the multi layer

### ISSUE THREAD

**Issue by coolmatt1024** [marcellacornia/mlnet#15]
Hi,

Your paper gives me some inspiration.I found you use three layers: conv3, conv4, conv5. So, when you just use conv5 or (conv4 and conv5), you get a worse result?

I did many experiments recently.To my big disappointment,  I found using multi-layer from vgg usually leads to a worse result(or not improved much), so can you give me some suggestions?

**Comment by marcellacornia** [comment]
Hi @coolmatt1024,
in our experiments, we did not notice the same behavior. Which dataset are you using?

**Comment by coolmatt1024** [comment]
I use SALICON, 10000 images for train, 5000 iamges for val.

Actually, now I am doing the experiment of ML-Net, to ensure whether the multi-layer outperform the single layer. In my previous experiments(my own saliency model), I didn't observe obvoius improvement.

**Comment by marcellacornia** [comment]
We did not perform experiments using the new version of the SALICON dataset (2017 release). So, I don't know if the previous results are confirmed.

However, in our paper (Sec. IV-B) you can find an analysis regarding the relative importance of activation maps coming from different levels of the CNN. As you can see, all features give a contribution to the final results.

**Comment by coolmatt1024** [comment]
I agree your analysis in Sec. IV-B. 

I have done the experiment as the repo did(block3, block4, block5), and finished the experiment just using block5.  Surprisingly, just using block5 got a better result. I am very confused about the result now.
