### ISSUE TITLE
pytorch

### ISSUE THREAD

**Issue by ghost** [marcellacornia/mlnet#18]
could you offer the pytorch code?
thanks.

**Comment by harrisonford** [comment]
Hi! I'm not the author but I'm gonna fork this repository and repackage it in the next two weeks, mainly using Tensorflow. I'll leave a bump in here in case something happens.

**Comment by immortal3** [comment]
@chenbolinstudent 
I implemented MLNet in Pytorch. 
Link : https://github.com/immortal3/MLNet-Pytorch

**Comment by baraldilorenzo** [comment]
@immortal3 great work! Thanks for the contribution, I think we will add a link to your implementation in the Readme :)
